### PR TITLE
Fixes for Issue #115 & updated packages

### PR DESCRIPTION
**Pull request by JijoBose**
PR contains:

- Fixes for Issue [Issue 115](https://github.com/abbasfreestyle/react-native-af-video-player/issues/115)
- gitignore file
- compatible with React Native 0.59

### CODE REVIEW

**Comment by skptricks** [comment]
Still it is not working...

**Comment by JijoBose** [comment]
> Still it is not working...

@skptricks  Are you still getting the same error or any different.
Let me know the error message

**Comment by skptricks** [comment]
> > Still it is not working...
> 
> @skptricks Are you still getting the same error or any different.
> Let me know the error message

I am getting below error message, while launching code in android device : 
Error:while updating property 'src' of a view managed by: RCTVideo

**Comment by JijoBose** [comment]
> > > Still it is not working...
> > 
> > 
> > @skptricks Are you still getting the same error or any different.
> > Let me know the error message
> 
> I am getting below error message, while launching code in android device :
> Error:while updating property 'src' of a view managed by: RCTVideo


This PR is not merged yet, so install this using

`npm install JijoBose/react-native-af-video-player#master`

Few dependent packages are updated to a newer version
First reset node_modules
`rm -rf node_modules && npm install`
and then link the dependency (as per readme)

```
react-native link react-native-video
react-native link react-native-keep-awake
react-native link react-native-vector-icons
react-native link react-native-orientation
react-native link react-native-linear-gradient
```

**Comment by BloLee** [comment]
我再次遇到这个问题 
"react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-af-video-player": "github:JijoBose/react-native-af-video-player#master",
    "react-native-fs": "^2.14.1",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-keep-awake": "^4.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-orientation": "^3.1.3",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.0.0",
    "react-navigation": "^3.11.1"
设备  android 

这是我的代码
[index1.txt](https://github.com/abbasfreestyle/react-native-af-video-player/files/3537233/index1.txt)

错误信息：
photo_2019-08-24_21-42-58
photo_2019-08-24_21-43-05

**Comment by ericchan3721** [comment]
> 我再次遇到这个问题
> "react": "16.8.6",
> "react-native": "0.60.4",
> "react-native-af-video-player": "github:JijoBose/react-native-af-video-player#master",
> "react-native-fs": "^2.14.1",
> "react-native-gesture-handler": "^1.3.0",
> "react-native-keep-awake": "^4.0.0",
> "react-native-linear-gradient": "^2.5.6",
> "react-native-orientation": "^3.1.3",
> "react-native-splash-screen": "^3.2.0",
> "react-native-vector-icons": "^6.6.0",
> "react-native-video": "^5.0.0",
> "react-navigation": "^3.11.1"
> 设备 android
> 
> 这是我的代码
> [index1.txt](https://github.com/abbasfreestyle/react-native-af-video-player/files/3537233/index1.txt)
> 
> 错误信息：
> ...

The possible solution by @randy-miller is available at Issue #68.

Simply modify the files ```ReactVideoView.java``` & ```ReactVideoViewManager.java``` can do the trick

Path for those java files: ```../node_modules/react-native-video/android/src/main/java/com/brentvatne/react```

**Comment by DevAelius** [comment]
@ericchan3721  after modifying the suggested files it's worked for android **especially android (9 pie).** 
**Thanks & appreciated.**

**Comment by ericchan3721** [comment]
> @ericchan3721 after modifying the suggested files it's worked for android **especially android (9 pie).**
> **Thanks & appreciated.**

I have tested on Android 10 (Emulator & real devices) and it should be works as well

**Comment by akhilsanker** [comment]
Hi 
Having the same issue. @ericchan3721 , not working.
Can you explain the workaround?

Thanks

**Pull request closed without merging**
